In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [10]:
df = pd.read_csv("Housing_Price.csv")

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [13]:
df.head()
df['furnishingstatus'].value_counts()

furnishingstatus
semi-furnished    227
unfurnished       178
furnished         140
Name: count, dtype: int64

In [8]:
label = LabelEncoder()
df['furnishingstatus_en'] = label.fit_transform(df['furnishingstatus'])

In [9]:
df.drop(columns=['furnishingstatus'])

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_en
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,0
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,0
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,1
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,0
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,2
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,1
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,2
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,0
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,2

In [15]:
d = {"age":[3,4,5,3,5],"place":['kerala','tamil','kerala','kerala','andra'],"code":[22,33,11,33,44]}

data = pd.DataFrame(d)

In [16]:
data.head()

   age   place  code
0    3  kerala    22
1    4   tamil    33
2    5  kerala    11
3    3  kerala    33
4    5   andra    44

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [19]:
scale = MinMaxScaler()
scale.fit_transform(data[['age','code']])

array([[0.        , 0.33333333],
       [0.5       , 0.66666667],
       [1.        , 0.        ],
       [0.        , 0.66666667],
       [1.        , 1.        ]])

In [20]:
data.head()

   age   place  code
0    3  kerala    22
1    4   tamil    33
2    5  kerala    11
3    3  kerala    33
4    5   andra    44